version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      # TODO: Use a secrets manager to securely store and retrieve the following sensitive information.
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Replace with a secure secrets manager in production.
      MYSQL_DATABASE: ${DB_NAME} # Replace with a secure secrets manager in production.
      MYSQL_USER: ${DB_USER} # Replace with a secure secrets manager in production.
      MYSQL_PASSWORD: ${DB_PASSWORD} # Replace with a secure secrets manager in production.
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    environment:
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.7.3
    environment:
      - LOKI_PORT=${LOKI_PORT}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  db_data: